# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - "0.6"
  - "1.0"
  - "nightly"
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'VERSION >= v\"0.7.0-DEV.3630\" && using Pkg; Pkg.clone(pwd()); Pkg.build("SIMD"); Pkg.test("SIMD"; coverage=true)'
after_success:
  - julia -e 'VERSION >= v\"0.7.0-DEV.3630\" && using Pkg; cd(Pkg.dir("SIMD")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
