language: julia
os:
  - osx
  - linux
julia:
  - 1
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
